[package]
name = "jin"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3.19", features = ["derive"] }
codespan-reporting = "0.11.1"
color-eyre = "0.6.2"
derive_more = "0.99.17"
ena = "0.14.2"
enum-as-inner = "0.6.0"
indexmap = "2.0.0"
owo-colors = "3.5.0"
path-absolutize = "3.1.0"
pretty = { version = "0.12.1" }
ptree = "0.4.0"
stopwatch = "0.0.7"
unindent = "0.2.2"
ustr = "0.10.0"

[target.'cfg(windows)'.dependencies]
libc = "0.2.132"
widestring = "1.0.2"
winapi = { version = "0.3.9", features = [
	"winuser",
	"impl-default",
	"oleauto",
] }
