[package]
name = "untitled"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.19", features = ["derive"] }
codespan-reporting = "0.11.1"
color-eyre = "0.6.2"
ena = "0.14.2"
enum-as-inner = "0.6.0"
owo-colors = "3.5.0"
path-absolutize = "3.1.0"
pretty = { version = "0.12.1" }
ptree = "0.4.0"
stopwatch = "0.0.7"
unindent = "0.2.2"
ustr = "0.10.0"
