[package]
name = "untitled"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.19", features = ["derive"] }
ena = "0.14.2"
miette = { version = "5.10.0", features = ["fancy"] }
owo-colors = "3.5.0"
ptree = "0.4.0"
slotmap = "1.0.6"
stopwatch = "0.0.7"
thiserror = "1.0.44"
ustr = "0.10.0"
