[package]
name = "untitled"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ariadne = { version = "0.3.0", features = ["auto-color"] }
clap = { version = "4.3.19", features = ["derive"] }
color-eyre = "0.6.2"
ena = "0.14.2"
ptree = "0.4.0"
slotmap = "1.0.6"
ustr = "0.10.0"
