[workspace]
members = ["compiler", "data_structures"]
resolver = "2"

[workspace.lints.clippy]
correctness = "warn"
suspicious = "warn"
style = "warn"
complexity = "warn"
perf = "warn"
pedantic = "warn"
similar_names = "allow"
module_name_repetitions = "allow"
too_many_lines = "allow"
missing_const_for_fn = "allow"
cast_possible_truncation = "allow"
wildcard_imports = "allow"
