max_width = 100
use_try_shorthand = true
reorder_imports = true
use_small_heuristics = "Max"
# imports_granularity = "Crate"
# group_imports = "StdExternalCrate"
# format_strings = true
# wrap_comments = false
