[package]
name = "compiler_parse"
version = "0.1.0"
edition = "2021"

[dependencies]
ena = "0.14.2"
owo-colors = "3.5.0"
path-absolutize = "3.1.0"
ptree = "0.4.0"
libc = "0.2"
internment = "0.7.4"
lazy_static = "1.4.0"
indexmap = "2.1.0"
bitflags = "2.4.2"
petgraph = "0.6.4"
graph-cycles = "0.1.0"
compiler_core = { path = "../compiler_core" }
compiler_data_structures = { path = "../compiler_data_structures" }
compiler_helpers = { path = "../compiler_helpers" }
codespan-reporting = { workspace = true }
ustr = { workspace = true }
typed-index-collections = { workspace = true }
rustc-hash = { workspace = true }
anyhow = { workspace = true }
camino = { workspace = true }
itertools = { workspace = true }

[lints]
workspace = true
