[package]
name = "compiler_data_structures"
version = "0.1.0"
edition = "2021"

[dependencies]
rustc-hash = { workspace = true }
typed-index-collections = { workspace = true }

[lints]
workspace = true
