on:
  push:
    branches:
      - main
name: Release Packaging
jobs:
  release:
    name: Release Packaging
    env:
      jin: rust_ci_github_actions_workflow
    runs-on: ubuntu-latest
    steps:
      - uses: rui314/setup-mold@v1
      - uses: goto-bus-stop/setup-zig@v2
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Release Build
        run: cargo build --release
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.jin }}
          path: target/release/${{ env.jin }}
